---
- name: Get Artifact Registry secret
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Store pull secret
    shell: |
      kubectl get secret artifact-registry-secret -o json | jq --sort-keys \
          'del(
            .metadata.annotations."kubectl.kubernetes.io/last-applied-configuration",
            .metadata.annotations."control-plane.alpha.kubernetes.io/leader",
            .metadata.uid,
            .metadata.selfLink,
            .metadata.resourceVersion,
            .metadata.creationTimestamp,
            .metadata.generation,
            .metadata.namespace,
            .metadata.managedFields
        )' > resource.json
